---

- name: Install vector from downloaded package
  when: not vector_install_from_repo | bool
  block:
    - name: Install vector (Debian)
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        deb: "https://apt.vector.dev/pool/v/ve/vector_{{ vector_version }}-1_{{ arch }}.deb"
        install_recommends: true
      notify: Restart vector
      vars:
        arch: "{{ vector_arch[ansible_machine] }}"

    - name: Install vector (RedHat)
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name: "https://yum.vector.dev/stable/vector-0/{{ arch }}/vector-{{ vector_version }}-1.{{ arch }}.rpm"
        state: present
        disable_gpg_check: true # package is not signed
      notify: Restart vector
      vars:
        arch: "{{ vector_arch[ansible_machine] }}"

- name: Install vector from repository
  when: vector_install_from_repo | bool
  block:
    - name: Install vector
      ansible.builtin.package:
        name: "{{ vector_package }}"
        state: present
