---

# vector configuration file
vector_template: vector.yaml.j2
vector_config_file: /etc/vector/vector.yaml

# vector restartsec vector_template
vector_restartsec_template: vector_restartsec.j2
vector_restartsec_config_dir: /etc/systemd/system/vector.service.d
vector_restartsec_config_file: vector.conf

# vector groups
# vector_groups: []

# install vector from repo
vector_install_from_repo: false
vector_repo:
  Debian: deb [signed-by=/usr/share/keyrings/datadog-archive-keyring.gpg] https://apt.vector.dev/ stable vector-0
  RedHat: https://yum.vector.dev/stable/vector-0/$basearch/
vector_repo_key:
  Debian:
    - https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public
    - https://keys.datadoghq.com/DATADOG_APT_KEY_F14F620E.public
    - https://keys.datadoghq.com/DATADOG_APT_KEY_C0962C7D.public
  RedHat:
    - https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public
    - https://keys.datadoghq.com/DATADOG_RPM_KEY_B01082D3.public
    - https://keys.datadoghq.com/DATADOG_RPM_KEY_FD4BF915.public
vector_repo_gpgcheck: true

# vector package name
vector_package: vector
